<a href="https://colab.research.google.com/github/PsorTheDoctor/robotics/blob/main/notebooks/quaternions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Kwaterniony i rotacje

In [ ]:
!pip install pyquaternion

In [6]:
from pyquaternion import Quaternion
import numpy as np
from math import *

angle = radians(30)

quaternion = Quaternion(axis=[1, 0, 0], angle=angle)
quaternion

Quaternion(0.9659258262890683, 0.25881904510252074, 0.0, 0.0)

In [7]:
array = np.array([1, 2, 3])

rotated = quaternion.rotate(array)
rotated

array([1.        , 0.23205081, 3.59807621])

In [27]:
def rotate_by_euler_angles(a, b, g):

  R = np.array([[cos(a) * cos(b), 
                 cos(a) * sin(b) * sin(g) - sin(a) * cos(g),
                 cos(a) * sin(b) * cos(g) + sin(a) * sin(g)],
                [sin(a) * cos(b),
                 sin(a) * sin(b) * sin(g) + cos(a) * cos(g),
                 sin(a) * sin(b) * cos(g) - cos(a) * sin(g)],
                [-sin(b),
                 cos(b) * sin(g),
                 cos(b) * cos(g)]])
  return R

def rotate_by_axis_and_angle(axis, theta):

  [ux, uy, uz] = axis
  c = cos(theta)
  s = sin(theta)

  R = np.array([[c + ux*ux*(1-c), ux*uy*(1-c) - uz*s, ux*uz*(1-c) + uy*s],
                [uy*ux*(1-c) + uz*s, c + uy*uy*(1-c), uy*uz*(1-c) - ux*s],
                [uz*ux*(1-c) - uy*s, uz*uy*(1-c) + ux*s, c + uz*uz*(1-c)]])
  return R

def rotate_by_quaternion(axis, theta):

  [a, b, c, d] = Quaternion(axis=axis, angle=theta)
  # axis = axis / np.sqrt(np.dot(axis, axis))
  # a = cos(theta / 2.)
  # [b, c, d] = -axis * sin(theta / 2.)

  R = np.array([[a*a+b*b-c*c-d*d, 2 * (b*c-a*d), 2 * (b*d+a*c)],
                [2 * (b*c+a*d), a*a+c*c-b*b-d*d, 2 * (c*d-a*b)],
                [2 * (b*d-a*c), 2 * (c*d+a*b), a*a+d*d-b*b-c*c]])
  return R

In [77]:
rotate_by_euler_angles(angle, 0, 0)

array([[ 0.8660254, -0.5      ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ],
       [-0.       ,  0.       ,  1.       ]])

In [75]:
rotate_by_axis_and_angle([1, 0, 0], angle)

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  0.8660254, -0.5      ],
       [ 0.       ,  0.5      ,  0.8660254]])

In [74]:
rotate_by_quaternion([1, 0, 0], angle)

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  0.8660254,  0.5      ],
       [ 0.       , -0.5      ,  0.8660254]])

In [82]:
A = np.array([[1, 2, 3], [4, 5, 6]])
R = rotate_by_quaternion([1, 0, 0], angle)
B = np.dot(A, R)

A_norm = A - np.mean(A, axis=0)
B_norm = B - np.mean(B, axis=0)

U, D, V = np.linalg.svd(np.dot(A_norm.T, B_norm))
R

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  0.8660254,  0.5      ],
       [ 0.       , -0.5      ,  0.8660254]])

In [83]:
S = np.identity(3)
R = np.dot(np.dot(U, S), V)
R

array([[-0.32399474,  0.11076318,  0.93955251],
       [ 0.56569999,  0.81869989,  0.0985597 ],
       [ 0.75829475, -0.56343767,  0.32791319]])

In [84]:
R = np.dot(V.T, U.T)
R

array([[-0.32399474,  0.56569999,  0.75829475],
       [ 0.11076318,  0.81869989, -0.56343767],
       [ 0.93955251,  0.0985597 ,  0.32791319]])